name: Verificação de Links

on:
  push:
    branches: [main]
    paths: ["**.md"]
  pull_request:
    branches: [main]
    paths: ["**.md"]
  schedule:
    - cron: "0 8 * * 1" # toda segunda-feira às 8h UTC

  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verificar links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --insecure
            --accept 200,204,301,302,403
            --timeout 60
            --max-retries 5
            --retry-wait-time 5
            --max-concurrency 2
            './**/*.md'
          fail: true
